namespace Resources.Next.Generator.Source;

internal static class SourceConstants
{
    public const string Namespace = "Resources.Next";
    public const string NamespaceDirective = $"namespace {Namespace};";

    public const string FileHeader =
        """
        // <auto-generated/>
        #nullable enable
        """;
}