name: publish to nuget
on:
  push:
    branches:
      - master

jobs:
  nuget-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://api.nuget.org/v3/index.json
          dotnet-version: 8.0.*
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build solution
        run: dotnet build -c Release --no-restore

      - name: Publish to NuGet
        run: |
          mkdir __out
          dotnet pack .\Resources.Next.Core\Resources.Next.csproj -c Release -o __out --no-restore
          dotnet nuget push "./__out/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}}
          rm -rf __out